import type { Metadata } from "next";
import { ClerkProvider } from "@clerk/nextjs";
// import { Geist, Geist_Mono } from "next/font/google";
import {IBM_Plex_Serif,Mona_Sans} from "next/font/google";


import "./globals.css";
import Navbar from "@/components/ui/Navbar";

const ibm = IBM_Plex_Serif({
  variable:'--font-ibm-plex-serif',
  subsets:['latin'],
  weight:['400','500','600','700'],
  display:'swap'
});
const mona = Mona_Sans({
  variable:'--font-mona-sans',
  subsets:['latin'],

  display:'swap'
});
// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({


  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${ibm.variable} ${mona.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <ClerkProvider>
          <Navbar/>
          {children}
        </ClerkProvider>
      </body>
    </html>
  );
}
